### ISSUE TITLE
Do we still need/want a Dry::Transaction Step adapter?

### ISSUE THREAD

**Issue by brianvh** [hashrabbit/dry-lifecycle#1]
Given the soon-to-be-coming change that will effectively decommission `Dry::Transaction`, in favor of the `Dry::Monads::Do` notation, I'm questioning whether creating a Step adapter for `Dry::Lifecycle` still makes sense.

It may be better for LeaseHash (definitely in the long-term) if I just convert all of the existing `Dry::Transaction` objects over to the Do notation, but I wanted to run the general idea by both of you, first…

@nealhhdotdev @rschifflin

**Comment by rschifflin** [comment]
Reading up on dry's Do notation, it's an impressive hack to get something Do-like into ruby syntax. I wonder if Dry::Transaction itself uses the Do-yield syntax to combine steps under the hood of its `#call` method. I don't see any obvious reasons we shouldn't switch over to Do-yield, the two choices seem to share the same constraints so we're not losing any flexibility

**Comment by nealhhdotdev** [comment]
I agree with @rschifflin .  Also,  my two cents would be that if we plan to eventually switch over to the `Dry::Monads::Do` notation and can still use `Dry::Lifecycle` in the meantime (and as we switch over) without creating a `Dry::Transaction` step adapter; we should go that route.
